const fs=require('fs'), vm=require('vm'), assert=require('assert/strict');
const version=fs.readFileSync(__dirname+'/../whatsapp-tracker.php','utf8').match(/define\( 'AWM_VERSION', '([^']+)'/)[1];
const code=fs.readFileSync(__dirname+'/../assets/frontend-tracker-'+version+'.js','utf8');
const rule=(extra={})=>({id:'r',name:'Notice',channel:'telephone',language:'en',matchMode:'all',pagePaths:[],destinations:['tel:+12025550101'],exactLinks:[],primaryAction:'url',primaryUrl:'/contact/',primaryLabel:'Contact',secondaryUrl:'tel:+12025550102',secondaryLabel:'Call',...extra});
function environment(rules=[], enabled=true, stale=rules, visibility={whatsapp:true,telephone:true}, plainText=''){
 const handlers={},nodes={},events=[],beacons=[],navigations=[],timers=[],intervals=[],generatedLinks=[];let overlay;
 const textParent={tagName:'P',closest(){return null;},replaceChild(fragment){for(const child of fragment.children||[])if(child.tagName==='A')generatedLinks.push(child);textNode.parentNode=null;}};
 const textNode={nodeValue:plainText,parentNode:textParent};let walked=false;
 const doc={hidden:false,readyState:'complete',activeElement:null,addEventListener(k,fn){handlers[k]=fn;},getElementById(){return {getAttribute(){return JSON.stringify({emergencyRules:stale,popupEnabled:visibility,configEndpoint:'/config',endpoint:'/track',language:'en'});}}},createElement(tag){if(tag==='a'){return {tagName:'A',href:'',className:'',textContent:'',attributes:{},setAttribute(k,v){this.attributes[k]=v;}};}const element=new Element('div');if(!overlay)overlay=element;return element;},createTextNode(value){return {nodeValue:value};},createDocumentFragment(){return {children:[],appendChild(child){this.children.push(child);}};},createTreeWalker(){walked=false;return {nextNode(){if(!plainText||walked)return null;walked=true;return textNode;}};},body:{appendChild(){},classList:{add(){},remove(){}}}};
 class Element{
  constructor(name){this.name=name;this.hidden=false;this.listeners={};this.textContent='';}
  addEventListener(k,f){this.listeners[k]=f;}
  querySelector(selector){return nodes[selector]||(nodes[selector]=new Element(selector));}
  querySelectorAll(){return ['.awm-emergency-close-x','.awm-emergency-primary','.awm-emergency-secondary','.awm-emergency-dismiss'].map(s=>this.querySelector(s)).filter(e=>!e.hidden);}
  appendChild(){} closest(){return null;} removeAttribute(k){delete this[k];} setAttribute(k,v){this[k]=v;} focus(){doc.activeElement=this;}
 }
 let settings={emergencyRules:rules,trackingEnabled:enabled,popupEnabled:visibility}, fail=false;
 const win={dataLayer:events,location:{href:'https://example.test/en/contact/',pathname:'/en/contact/',assign(u){navigations.push(u);}},fetch:()=>{},setTimeout(f){timers.push(f);return timers.length;},clearTimeout(){},setInterval(f){intervals.push(f);},addEventListener(k,f){handlers[k]=f;}};
 const context={document:doc,window:win,navigator:{sendBeacon(u,b){beacons.push({u,b});return true;}},URL,Blob,AbortController,Date,fetch:async()=>{if(fail)throw Error('offline');return {ok:true,json:async()=>settings};}};
 vm.runInNewContext(code,context);
 function activate(type,href,extra={},link){const a=link||{href,textContent:'Contact',getAttribute(k){return k==='href'?href:extra[k]||'';},focus(){doc.activeElement=a;}};const ev={type,target:{closest(){return a;}},preventDefault(){this.prevented=true;},stopImmediatePropagation(){this.stopped=true;}};handlers[type](ev);return {event:ev,link:a};}
 return {events,beacons,navigations,generatedLinks,doc,nodes,win,handlers,intervals, async ready(){for(let i=0;i<8;i++) await Promise.resolve();},get overlay(){return overlay;},setSettings(s){settings=s;},fail(){fail=true;},refresh(){context.Date={now:()=>Date.now()+10000};intervals[0]();},click(href,extra={},link){return activate('click',href,extra,link).event;},touchStart(href,extra={},link){return activate('touchstart',href,extra,link);},touchEnd(href,extra={},link){return activate('touchend',href,extra,link);}};
}
let count=0;
async function test(name,f){await f();count++;console.log('PASS '+name);}
(async()=>{
 await test('Telephone formatting and distinct event',async()=>{const e=environment([rule()]);await e.ready();assert.ok(e.click('tel:+1 (202) 555-0101').prevented);assert.equal(e.events[0].event,'telephone_emergency_popup');assert.equal(e.beacons.length,0);});
 await test('Telephone short codes and exempt links bypass popup',async()=>{const e=environment([rule({pagePaths:['*'],destinations:[]})]);await e.ready();for(const href of ['tel:999','tel:112','tel:911','tel:123456'])assert.ok(!e.click(href).prevented);assert.ok(!e.click('tel:+12025550101',{'data-awm-emergency-exempt':'1'}).prevented);});
 await test('Local number and extension do not conflate',async()=>{const e=environment([rule()]);await e.ready();for(const h of ['tel:2025550101','tel:+12025550101;ext=123'])assert.ok(!e.click(h).prevented);});
 await test('Exact tel link canonicalization matches extension',async()=>{const e=environment([rule({destinations:[],exactLinks:['tel:+1 (202) 555-0101;ext=123']})]);await e.ready();assert.ok(e.click('tel:+12025550101;ext=123').prevented);});
 await test('Legacy rules retain WhatsApp-only behaviour',async()=>{const e=environment([rule({channel:undefined,destinations:[],pagePaths:['*']})]);await e.ready();assert.ok(!e.click('tel:+12025550101').prevented);assert.ok(e.click('https://wa.me/12025550101').prevented);});
 await test('Both channels supported without destination collisions',async()=>{const e=environment([rule({channel:'both',destinations:['tel:+12025550101','12025550101']})]);await e.ready();assert.ok(e.click('tel:+12025550101').prevented);assert.ok(e.click('https://wa.me/12025550101').prevented);});
 await test('Language restriction wins over any target match',async()=>{const e=environment([rule({language:'zh',matchMode:'any',pagePaths:['*']})]);await e.ready();assert.ok(!e.click('tel:+12025550101').prevented);});
 await test('All requires path and destination',async()=>{const e=environment([rule({pagePaths:['/zh/*']})]);await e.ready();assert.ok(!e.click('tel:+12025550101').prevented);});
 await test('Tracking disabled suppresses clicks, popup and alternative events',async()=>{const e=environment([rule()],false);await e.ready();e.click('https://wa.me/12025550101');e.click('tel:+12025550103');e.click('tel:+12025550101');e.nodes['.awm-emergency-secondary'].listeners.click();assert.equal(e.events.length,0);assert.equal(e.beacons.length,0);assert.equal(e.navigations[0],'tel:+12025550102');});
 await test('Normal WhatsApp tracking preserved once per click',async()=>{const e=environment();await e.ready();e.click('https://wa.me/12025550101');assert.equal(e.events.length,1);assert.equal(e.events[0].event,'whatsapp_click');assert.equal(e.beacons.length,1);});
 await test('Normal telephone click is dataLayer-only',async()=>{const e=environment();await e.ready();e.click('tel:+12025550101');assert.equal(e.events[0].event,'telephone_click');assert.equal(e.beacons.length,0);});
 await test('Fresh enabled rule overrides empty cached settings',async()=>{const e=environment([rule()],true,[]);await e.ready();assert.ok(e.click('tel:+12025550101').prevented);});
 await test('Fresh removal overrides cached emergency rule',async()=>{const e=environment([],true,[rule()]);await e.ready();assert.ok(!e.click('tel:+12025550101').prevented);});
 await test('Refresh closes a removed active rule without duplicate event',async()=>{const e=environment([rule()]);await e.ready();e.click('tel:+12025550101');e.setSettings({emergencyRules:[],trackingEnabled:false});e.refresh();await e.ready();assert.ok(e.overlay.hidden);assert.equal(e.events.length,1);e.click('https://wa.me/12025550101');assert.equal(e.events.length,1);});
 await test('Tawk throws then URL fallback still runs',async()=>{const e=environment([rule({primaryAction:'tawk'})]);await e.ready();e.win.Tawk_API={maximize(){throw Error('widget failure');}};e.click('tel:+12025550101');e.nodes['.awm-emergency-primary'].listeners.click();assert.equal(e.navigations[0],'/contact/');assert.ok(e.overlay.hidden);});
 await test('Tawk success closes popup without fallback navigation',async()=>{const e=environment([rule({primaryAction:'tawk'})]);await e.ready();let called=false;e.win.Tawk_API={maximize(){called=true;}};e.click('tel:+12025550101');e.nodes['.awm-emergency-primary'].listeners.click();assert.ok(called);assert.ok(e.overlay.hidden);assert.equal(e.navigations.length,0);});
 await test('Shift Tab from dialog container wraps to final visible control',async()=>{const e=environment([rule()]);await e.ready();e.click('tel:+12025550101');e.doc.activeElement=e.overlay;let prevented=false;e.overlay.listeners.keydown({key:'Tab',shiftKey:true,preventDefault(){prevented=true;}});assert.ok(prevented);assert.equal(e.doc.activeElement,e.nodes['.awm-emergency-secondary']);});
 await test('Failed settings request suppresses subsequent tracking',async()=>{const e=environment([rule()]);await e.ready();e.fail();e.refresh();await e.ready();e.click('https://wa.me/12025550101');assert.equal(e.events.length,0);assert.equal(e.beacons.length,0);assert.ok(e.click('tel:+12025550101').prevented);});

 await test('Reported tel link blocks with exact target',async()=>{const e=environment([rule({destinations:['tel:+12025550104']})]);await e.ready();assert.ok(e.click('tel:+12025550104').prevented);assert.equal(e.navigations.length,0);assert.equal(e.events[0].event,'telephone_emergency_popup');});
 await test('Telephone number targets ignore only leading plus in both directions',async()=>{for(const [target,href] of [['tel:12025550104','tel:+12025550104'],['tel:+12025550104','tel:12025550104']]){const e=environment([rule({destinations:[target]})]);await e.ready();assert.ok(e.click(href).prevented);assert.equal(e.navigations.length,0);}});
 await test('Both channel numeric target also matches telephone',async()=>{const e=environment([rule({channel:'both',destinations:['12025550104']})]);await e.ready();assert.ok(e.click('tel:+12025550104').prevented);assert.ok(e.click('https://wa.me/12025550104').prevented);});
 await test('WhatsApp-only numeric target never blocks telephone',async()=>{const e=environment([rule({channel:'whatsapp',destinations:['12025550104']})]);await e.ready();assert.ok(!e.click('tel:+12025550104').prevented);});
 await test('Exact telephone URL retains leading-plus distinction',async()=>{const e=environment([rule({destinations:[],exactLinks:['tel:12025550104']})]);await e.ready();assert.ok(!e.click('tel:+12025550104').prevented);});
 await test('Plus-insensitive matching still respects extension and language',async()=>{const e=environment([rule({destinations:['tel:12025550104;ext=0']})]);await e.ready();assert.ok(e.click('tel:+12025550104;ext=0').prevented);assert.ok(!e.click('tel:+12025550104;ext=1').prevented);const z=environment([rule({destinations:['tel:12025550104'],language:'zh'})]);await z.ready();assert.ok(!z.click('tel:+12025550104').prevented);});
 await test('Reported number cannot dial until an alternative action is chosen',async()=>{const e=environment([rule({destinations:['tel:12025550104'],secondaryUrl:'tel:+12025550102'})]);await e.ready();e.click('tel:+12025550104');assert.equal(e.navigations.length,0);e.nodes['.awm-emergency-secondary'].listeners.click();assert.deepEqual(e.navigations,['tel:+12025550102']);assert.equal(e.events[1].event,'telephone_alternative_channel_click');});
 await test('Telephone popup master checkbox restores normal dialing',async()=>{const e=environment([rule()],true,[rule()],{whatsapp:true,telephone:false});await e.ready();const click=e.click('tel:+12025550101');assert.ok(!click.prevented);assert.equal(e.events[0].event,'telephone_click');});
 await test('WhatsApp popup master checkbox is independent',async()=>{const both=rule({channel:'both',destinations:['tel:+12025550101','12025550101']});const e=environment([both],true,[both],{whatsapp:false,telephone:true});await e.ready();assert.ok(!e.click('https://wa.me/12025550101').prevented);assert.ok(e.click('tel:+12025550101').prevented);});
 await test('Mobile touchstart blocks dialing before site handlers and suppresses follow-up events',async()=>{const e=environment([rule()]);await e.ready();const start=e.touchStart('tel:+12025550101');assert.ok(start.event.prevented);assert.ok(start.event.stopped);assert.equal(e.events.length,1);const end=e.touchEnd('tel:+12025550101',{},start.link);assert.ok(end.event.prevented);assert.ok(end.event.stopped);const click=e.click('tel:+12025550101',{},start.link);assert.ok(click.prevented);assert.ok(click.stopped);assert.equal(e.events.length,1);assert.equal(e.navigations.length,0);});
 await test('Page-wide rule intercepts a synthetic local URL before refresh',async()=>{const liveRule=rule({language:'',matchMode:'any',pagePaths:['/en/contact/'],destinations:['tel:+442079460900'],exactLinks:['tel:+442079460900']});const e=environment([liveRule]);assert.ok(e.click('tel:020 7946 0900').prevented);assert.equal(e.navigations.length,0);});
 await test('Scoped rule blocks fictional local and international fixtures only',async()=>{const scoped=rule({language:'',matchMode:'all',pagePaths:['/en/contact/'],destinations:['tel:+442079460900','tel:02079460900'],exactLinks:[]});const e=environment([scoped]);await e.ready();for(const href of ['tel:020 7946 0900','tel:+442079460900','tel:442079460900'])assert.ok(e.click(href).prevented,href);for(const href of ['tel:202 555 0105','tel:202 555 0106','tel:202 555 0107','tel:+12025550105','tel:+12025550106','tel:+12025550107'])assert.ok(!e.click(href).prevented,href);e.win.location.pathname='/another-page/';assert.ok(!e.click('tel:02079460900').prevented);});
 await test('Native tel destination is disabled only for matched fictional number and restored when popup is off',async()=>{const scoped=rule({language:'',destinations:['tel:02079460900']});const e=environment([scoped]);const attrs={href:'tel:020 7946 0900'};const a={closest(){return null;},getAttribute(k){return attrs[k]||null;},setAttribute(k,v){attrs[k]=v;},removeAttribute(k){delete attrs[k];}};e.doc.querySelectorAll=()=>[a];await e.ready();assert.equal(attrs.href,'#awm-telephone-notice');assert.equal(attrs['data-awm-original-tel'],'tel:020 7946 0900');e.setSettings({emergencyRules:[scoped],trackingEnabled:true,popupEnabled:{whatsapp:true,telephone:false}});e.refresh();await e.ready();assert.equal(attrs.href,'tel:020 7946 0900');assert.ok(!attrs['data-awm-original-tel']);});
 await test('Matching language takes precedence over more specific default',async()=>{const e=environment([rule({language:'',title:'Default',exactLinks:['tel:+12025550101'],priority:999}),rule({title:'English'})]);await e.ready();e.click('tel:+12025550101');assert.equal(e.nodes['.awm-emergency-title'].textContent,'English');});
 await test('Default is used when translated rule does not match the target',async()=>{const e=environment([rule({language:'',title:'Default'}),rule({title:'English',destinations:['tel:+12025550100']})]);await e.ready();e.click('tel:+12025550101');assert.equal(e.nodes['.awm-emergency-title'].textContent,'Default');});
 await test('Optional action hidden for existing rules; X still closes',async()=>{const e=environment([rule()]);await e.ready();e.click('tel:+12025550101');assert.equal(e.nodes['.awm-emergency-dismiss'].hidden,true);e.nodes['.awm-emergency-close-x'].listeners.click();assert.equal(e.overlay.hidden,true);});
 await test('Third telephone action goes directly to configured number',async()=>{const e=environment([rule({thirdEnabled:true,thirdLabel:'Other line',thirdAction:'url',thirdUrl:'tel:+12025550100'})]);await e.ready();e.click('tel:+12025550101');assert.equal(e.nodes['.awm-emergency-dismiss'].hidden,false);e.nodes['.awm-emergency-dismiss'].listeners.click();assert.deepEqual(e.navigations,['tel:+12025550100']);});
 await test('Shortcode action opens same-site frame and Back restores notice',async()=>{const r=rule({thirdEnabled:true,thirdLabel:'Enquiry',thirdAction:'shortcode',thirdFormUrl:'https://example.test/?awm_notice_form=r'});const e=environment([r]);await e.ready();e.click('tel:+12025550101');e.nodes['.awm-emergency-dismiss'].listeners.click();assert.equal(e.nodes['.awm-emergency-actions'].hidden,true);assert.ok(e.nodes['.awm-emergency-form'].src.includes('lang=en'));e.refresh();await e.ready();assert.ok(e.nodes['.awm-emergency-form'].src);e.nodes['.awm-emergency-back'].listeners.click();assert.equal(e.nodes['.awm-emergency-actions'].hidden,false);assert.equal(e.nodes['.awm-emergency-form'].src,undefined);});
 await test('Cross-origin form URL cannot be loaded',async()=>{const e=environment([rule({thirdEnabled:true,thirdLabel:'Form',thirdAction:'shortcode',thirdFormUrl:'https://other.example/form'})]);await e.ready();e.click('tel:+12025550101');e.nodes['.awm-emergency-dismiss'].listeners.click();assert.equal(e.nodes['.awm-emergency-form'].src,undefined);});
 console.log(`${count} frontend regression checks passed`);
})().catch(e=>{console.error(e);process.exit(1);});
